# Generated by Django 3.0.8 on 2020-08-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200820_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_set_book', 'Set changes book'),)},
        ),
    ]
